## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.full(10, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Создать вектор размера 10, заполненный единицами

In [5]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
np.full(10, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Создать вектор размера 10, заполненный числом 2.5

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [8]:
vect=np.full(10, 0)
vect[4]=1
print(vect)

[0 0 0 0 1 0 0 0 0 0]


Развернуть вектор (первый становится последним)

In [9]:
normal_vector=np.arange(1, 10, dtype=int)
print(normal_vector)
# Развернуть вектор
print(normal_vector[::-1])


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [10]:
vect=np.arange(0,9)
vect.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [11]:
example_vector=np.array([0,2,0,0,4,0])
# Return index
np.nonzero(example_vector)

(array([1, 4]),)

Создать 3x3 единичную матрицу

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [15]:
np.random.rand(3,3)

array([[ 0.40276276,  0.57953627,  0.10667783],
       [ 0.6076177 ,  0.09836866,  0.38785322],
       [ 0.60934575,  0.09792459,  0.23843812]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [18]:
test_vector = np.random.randint(low=1,high=100, size=30)
np.average(test_vector)

39.333333333333336

Перемножить матрицы 5x3 и 3x2

In [20]:
a=np.full((5,3),1)
b=np.full((3,2),2)

np.dot(a, b)

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [38]:
vect10=np.linspace(0,1,12)[1:-1]
print(vect10)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


Заменить максимальный элемент на ноль

In [39]:
value=np.max(vect10 )
index = np.argmax(vect10)
vect10[index]=0.0
vect10

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.        ])

Преобразовать массив из float в int

In [40]:
x = np.array([1, 2, 2.5])
print(x)

x.astype(int)

[ 1.   2.   2.5]


array([1, 2, 2])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [41]:
import scipy.spatial

Z = np.random.random((10,2))
print(Z)
print('***************Result:*********************')
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.99281557  0.73104805]
 [ 0.61869074  0.71615588]
 [ 0.8471559   0.86918402]
 [ 0.55544774  0.37991512]
 [ 0.91239583  0.39313401]
 [ 0.8538145   0.7987796 ]
 [ 0.79902154  0.97172962]
 [ 0.0296522   0.37818926]
 [ 0.93129084  0.10530018]
 [ 0.35794755  0.37628039]]
***************Result:*********************
[[ 0.          0.37442111  0.20074433  0.56087873  0.34735174  0.1546249
   0.30900445  1.02576459  0.6287652   0.72726713]
 [ 0.37442111  0.          0.27497989  0.34213671  0.43658425  0.2492185
   0.31278928  0.67910812  0.68619495  0.42837175]
 [ 0.20074433  0.27497989  0.          0.56962944  0.48049959  0.07071859
   0.1132807   0.95361845  0.76850322  0.69446295]
 [ 0.56087873  0.34213671  0.56962944  0.          0.35719277  0.51426664
   0.63997859  0.52579838  0.46547975  0.19753363]
 [ 0.34735174  0.43658425  0.48049959  0.35719277  0.          0.40985377
   0.58959868  0.88287012  0.28845335  0.55470436]
 [ 0.1546249   0.2492185   0.07071859  0.51426664  0.40985377 

Случайно расположить p элементов в 2D массив

In [42]:
n = 10
p = 3
Z = np.zeros((n,n))
print(Z)
print('************Result:********************')
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
************Result:********************
[[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [43]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
print('*************Result:**************')
Z0[::nz+1] = Z
print(Z0)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
*************Result:**************
[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

In [45]:
Z = np.random.randint(0,10,50)
print(Z)

print('*********Result:*************')

Z=np.array([1,2,3,1,2,3, 10,10, 10])
print(Z)
BC=np.bincount(Z)
print(BC)
BC.argmax()

[5 0 7 0 5 1 4 3 1 7 2 4 7 7 9 6 1 2 0 2 9 9 1 1 5 0 9 2 4 4 9 6 7 2 5 5 9
 0 2 4 6 4 5 8 2 7 3 3 5 9]
*********Result:*************
[ 1  2  3  1  2  3 10 10 10]
[0 2 2 2 0 0 0 0 0 0 3]


10

Найти n наибольших значений в массиве

In [47]:
Z = np.arange(30)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[27 28 29 26 25]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [14]:
import pandas as pd
food = pd.read_csv('en.openfoodfacts.org.products.tsv',  sep='\t', header=0)

/home/airat/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [16]:
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [17]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [18]:
food.shape[1]

163

Напечатайте все названия столбцов

In [19]:
food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [20]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [21]:
column_105 = food[food.columns[104]]
column_105.ftype

'float64:dense'

Как проиндексирован набор данных?

In [22]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [23]:
food['product_name'][18]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [1]:
import pandas as pd
chipo = pd.read_csv('chipotle.tsv',  sep='\t', header=0)


In [10]:
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

**Мой комментарий**

> Так как из задания трудно понять стоимость больше 10$ за единицу товара или с учетом количества товара сделал доработкую. 

### Предоставил три решения:

**1.** стоимость больше 10$ за единицу товара.

**2.** стоимость больше 10$ за **с учетом количества товара**


**3.** стоимость больше 10$ за **с учетом количества товара** только ``price_item`` это будет **общая стоимость товара** 


In [11]:
# Фильтруем поле "item_price" удаляем знак '$'. Далее преобразуем во float
# стоимость больше 10$ за единицу товара.
item_prices_more_10_dollars = chipo.item_price.str.replace('$','').astype(float) > 10.00

item_prices_more_10_dollars.value_counts()[True]

1130

In [12]:
# Фильтруем поле "item_price" удаляем знак '$'. Далее преобразуем во float
# стоимость больше 10$ за с учетом количества товара
item_prices_float = chipo.item_price.str.replace('$','').astype(float)

product_procr_in_bucket = item_prices_float * chipo.quantity.astype(float) > 10
product_procr_in_bucket.value_counts()[True]

1184

In [14]:
# Фильтруем поле "item_price" удаляем знак '$'. Далее преобразуем во float
# стоимость больше 10$ за с учетом количества товара
# с учетом количества товара только price_item это будет общая стоимость товара
item_prices_float = chipo.item_price.str.replace('$','').astype(float)

product_procr_in_bucket = item_prices_float / chipo.quantity.astype(float) > 10
product_procr_in_bucket.value_counts()[True]

1034

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

**Татьяна,**
* **1.** Вот тут считаю общую цену с учетом количества.

* **2.** Татьяна вы писали:

> Так и не посчитали стоимость каждого товара (там количество не всегда один, от этого ответы с количеством товаров определенной цены - неправильные). 

Решил добавить price (общую цену с учетом количества.)

* **3** Татьяна вы писали:
>...Нужно учиться выводить не датафрейм с ценой, а число. Это часто может пригодиться в вычислениях.

поэтому ниже добавил вывод только ``не датафрейм с ценой, а число``



In [55]:
# Вот тут считаю общую цену с учетом количества.
chipo['price'] = chipo.quantity.astype(float) * chipo.item_price.str.replace('$','').astype(float)

# В задании написано напечатоть столбцы item_name и item_price.
# Решил добавить price (общую цену с учетом количества.). Выводим DataFrame. 
# Ниже реализация выводи только числа
chipo_price=chipo[['item_name', 'item_price', 'price']]
print('Type: ' + str(type(chipo_price)))
chipo_price

Type: <class 'pandas.core.frame.DataFrame'>


item_name item_price  price
0              Chips and Fresh Tomato Salsa     $2.39    2.39
1                                      Izze     $3.39    3.39
2                          Nantucket Nectar     $3.39    3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39    2.39
4                              Chicken Bowl    $16.98   33.96
5                              Chicken Bowl    $10.98   10.98
6                             Side of Chips     $1.69    1.69
7                             Steak Burrito    $11.75   11.75
8                          Steak Soft Tacos     $9.25    9.25
9                             Steak Burrito     $9.25    9.25
10                      Chips and Guacamole     $4.45    4.45
11                     Chicken Crispy Tacos     $8.75    8.75
12                       Chicken Soft Tacos     $8.75    8.75
13                             Chicken Bowl    $11.25   11.25
14                      Chips and Guacamole     $4.45    4.45
15    Chips and Tomatillo-Green Chili Salsa     $2.39    2.39
16                          Chicken Burrito     $8.49    8.49
17                          Chicken Burrito     $8.49    8.49
18                              Canned Soda     $2.18    4.36
19                             Chicken Bowl     $8.75    8.75
20                      Chips and Guacamole     $4.45    4.45
21                         Barbacoa Burrito     $8.99    8.99
22                         Nantucket Nectar     $3.39    3.39
23                          Chicken Burrito    $10.98   10.98
24                                     Izze     $3.39    3.39
25             Chips and Fresh Tomato Salsa     $2.39    2.39
26                             Chicken Bowl     $8.49    8.49
27                         Carnitas Burrito     $8.99    8.99
28                              Canned Soda     $1.09    1.09
29                          Chicken Burrito     $8.49    8.49
...                                     ...        ...    ...
4592                       Barbacoa Burrito    $11.75   11.75
4593                          Carnitas Bowl    $11.75   11.75
4594                          Barbacoa Bowl    $11.75   11.75
4595                           Chicken Bowl     $8.75    8.75
4596                    Chips and Guacamole     $4.45    4.45
4597                      Canned Soft Drink     $1.25    1.25
4598                          Bottled Water     $1.50    1.50
4599                           Chicken Bowl     $8.75    8.75
4600                    Chips and Guacamole     $4.45    4.45
4601                      Canned Soft Drink     $1.25    1.25
4602                       Barbacoa Burrito     $9.25    9.25
4603                       Barbacoa Burrito     $9.25    9.25
4604                           Chicken Bowl     $8.75    8.75
4605                    Chips and Guacamole     $4.45    4.45
4606                      Canned Soft Drink     $1.25    1.25
4607                          Steak Burrito    $11.75   11.75
4608                         Veggie Burrito    $11.25   11.25
4609                      Canned Soft Drink     $1.25    1.25
4610                          Steak Burrito    $11.75   11.75
4611                         Veggie Burrito    $11.25   11.25
4612                          Carnitas Bowl     $9.25    9.25
4613                                  Chips     $2.15    2.15
4614                          Bottled Water     $1.50    1.50
4615                     Chicken Soft Tacos     $8.75    8.75
4616                    Chips and Guacamole     $4.45    4.45
4617                          Steak Burrito    $11.75   11.75
4618                          Steak Burrito    $11.75   11.75
4619                     Chicken Salad Bowl    $11.25   11.25
4620                     Chicken Salad Bowl     $8.75    8.75
4621                     Chicken Salad Bowl     $8.75    8.75

[4622 rows x 3 columns]

* **3** Татьяна вы писали
>...Нужно учиться выводить не датафрейм с ценой, а число. Это часто может пригодиться в вычислениях.

поэтому ниже добавил вывод только ``не датафрейм с ценой, а число``

In [62]:
for item_name, item_price, price, i in zip(chipo_price.item_name, chipo.item_price, chipo.price, range(10)):
    if i > 10:
        break
    print( '{} | {} | {}'.format(item_name,item_price, price))

Chips and Fresh Tomato Salsa | $2.39  | 2.39
Izze | $3.39  | 3.39
Nantucket Nectar | $3.39  | 3.39
Chips and Tomatillo-Green Chili Salsa | $2.39  | 2.39
Chicken Bowl | $16.98  | 33.96
Chicken Bowl | $10.98  | 10.98
Side of Chips | $1.69  | 1.69
Steak Burrito | $11.75  | 11.75
Steak Soft Tacos | $9.25  | 9.25
Steak Burrito | $9.25  | 9.25


Отсортировать по имени предмета

In [63]:
chipo.sort_values(by='item_name', axis=0)

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  price  
3389                                        [Diet Coke]    $12.98   25.96  
341                                         [Diet Coke]     $6.49    6.49  
1849                                             [Coke]     $6.49    6.49  
1860                                        [Diet Coke]     $6.49    6.49  
2713                                             [Coke]     $6.49    6.49  
3422                                             [Coke]     $6.49    6.49  
553                                         [Diet Coke]     $6.49    6.49  
1916                                        [Diet Coke]     $6.49    6.49  
1922                                             [Coke]     $6.49    6.49  
1937                                        [Diet Coke]     $6.49    6.49  
3836                                             [Coke]     $6.49    6.49  
298                                            [Sprite]     $6.49    6.49  
1976                                        [Diet Coke]     $6.49    6.49  
1167                       

Сколько было заказано самого дорогого предмета?

In [64]:
max_item_prices=chipo.item_price.str.replace('$','').astype(float).max()
sum = chipo[chipo.item_price.str.replace('$','').astype(float) == max_item_prices].agg({'quantity' : ['sum']})

Татьяна вы писали:
>"Нужно учиться выводить не датафрейм с ценой, а число. Это часто может пригодиться в вычислениях."

In [65]:
sum['quantity']['sum']

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [44]:
chipo[chipo.item_name=='Veggie Salad Bowl'].agg({'quantity' : ['sum']})['quantity']['sum']

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [169]:
item_canned_soda_more_than_one_quantity = np.logical_and(chipo.item_name.astype(str)=='Canned Soda', chipo.quantity > 1)

chipo[item_canned_soda_more_than_one_quantity].shape[0]

20